# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: qBittorrent-Wireguard"
  org.opencontainers.image.description: "qBittorrent with WireGuard and automatic Port Forwarding for ProtonVPN."
  org.opencontainers.image.source: "https://github.com/Computerdores/hassio-addons"
  org.opencontainers.image.licenses: "MIT"
